--- # 1 Deploy Postgres (on instance C)
- name: Deploy postgres on db host
  hosts: db # run ONLY on the inventory group [db]
  become: true # use sudo
  tasks:
    - name: Create postgres volume  # Create volume (persistent data)
      community.docker.docker_volume:
        name: db-data

    - name: Run postgres container
      community.docker.docker_container: # Runs a container named db from image postgres:15-alpine.
        name: db
        image: postgres:15-alpine
        pull: true  # pull latest version of the tag 
        recreate: true # means if config changes → container gets recreated.
        restart: true # Ansible will restart it when needed.
        state: started  # ensures container is running.
        restart_policy: unless-stopped  # auto-start after reboot unless I manually stopped it
        published_ports:
          - "5432:5432"  # Maps host port 5432 → container port 5432.
        env:  # Standard postgres container env vars for initial DB init.
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "postgres"
        volumes:
          - "db-data:/var/lib/postgresql/data"  # persistent storage mapping
# 2 Deploy Redis + Worker (on instance B)
- name: Deploy redis + worker on backend host
  hosts: backend
  become: true
  tasks:
    - name: Create docker network (shared)
      community.docker.docker_network:
        name: back-tier  # Creates a Docker network called back-tier.

    - name: Create redis volume
      community.docker.docker_volume:
        name: redis-data

    - name: Run redis container
      community.docker.docker_container:
        name: redis
        image: redis:alpine
        pull: true
        recreate: true
        restart: true
        state: started
        restart_policy: unless-stopped
        published_ports:  # Exposes redis on the host’s port 6379 (so Vote on instance A can connect via backend private IP).
          - "6379:6379"
        volumes:
          - "redis-data:/data"
        networks:
          - name: back-tier

    - name: Wait for Postgres to be reachable from backend # This prevents worker starting before DB is ready.
      ansible.builtin.wait_for:
        host: "{{ hostvars['musti-c'].ansible_host }}"
        port: 5432
        timeout: 120  # It blocks up to 120 seconds until 10.10.2.111:5432 is reachable from B.

    - name: Run worker container
      community.docker.docker_container:
        name: worker
        image: bennay/worker:latest
        pull: true
        recreate: true
        restart: true
        state: started
        restart_policy: unless-stopped
        env:
          REDIS_HOST: "redis"
          DB_HOST: "{{ hostvars['musti-c'].ansible_host }}"
          DB_USERNAME: "postgres"
          DB_PASSWORD: "postgres"
          DB_NAME: "postgres"
        networks:
          - name: back-tier
# 3 Deploy Vote + Result (on instance A)
- name: Deploy vote + result on frontend host
  hosts: frontend
  become: true
  tasks:
    - name: Wait for Redis to be reachable from frontend
      ansible.builtin.wait_for:
        host: "{{ hostvars['musti-b'].ansible_host }}"
        port: 6379
        timeout: 120

    - name: Wait for Postgres to be reachable from frontend
      ansible.builtin.wait_for:
        host: "{{ hostvars['musti-c'].ansible_host }}"
        port: 5432
        timeout: 120

    - name: Run vote container
      community.docker.docker_container:
        name: vote
        image: bennay/vote:latest
        pull: true
        recreate: true
        restart: true
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "8080:80" # Exposes vote on http://<A_public_ip>:8080
        env:
          REDIS_HOST: "{{ hostvars['musti-b'].ansible_host }}"

    - name: Run result container
      community.docker.docker_container:
        name: result
        image: bennay/result:latest
        pull: true
        recreate: true
        restart: true
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "8081:80"  # Exposes result on http://<A_public_ip>:8081
        env:
          PG_HOST: "{{ hostvars['musti-c'].ansible_host }}"
          PG_PORT: "5432"
          PG_USER: "postgres"
          PG_PASSWORD: "postgres"
          PG_DATABASE: "postgres"